# -*- coding: utf-8 -*-
"""bank customers segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eHbQoXi-CYx41R5gyMrTCnj5n6rPwK3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("bank.csv", sep=';')

df = df.dropna()
df_encoded = pd.get_dummies(df, drop_first=True)

scaler = StandardScaler()
scaled = scaler.fit_transform(df_encoded)

inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled)
    inertia.append(kmeans.inertia_)

plt.plot(range(1, 11), inertia, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("Inertia")
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(scaled)
df_encoded['Cluster'] = kmeans.labels_

cluster_summary = df_encoded.groupby('Cluster').mean(numeric_only=True)
print(cluster_summary)

print(df_encoded['Cluster'].value_counts())

sns.barplot(x='Cluster', y='balance', data=df_encoded)
plt.title("Average Balance per Cluster")
plt.show()

sns.boxplot(x='Cluster', y='age', data=df_encoded)
plt.title("Age Distribution per Cluster")
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_components = pca.fit_transform(scaled)

df_encoded['PCA1'] = pca_components[:, 0]
df_encoded['PCA2'] = pca_components[:, 1]

plt.figure(figsize=(8, 6))
sns.scatterplot(data=df_encoded, x='PCA1', y='PCA2', hue='Cluster', palette='viridis')
plt.title("Customer Segments (PCA Scatter Plot)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.legend(title='Cluster')
plt.show()